
import { CropType, Stage, Customer, Transaction } from './types';

export const INITIAL_CROPS: CropType[] = [
  {
    id: 'adzuki',
    name: 'Adzuki Bean',
    scientificName: 'Vigna angularis',
    difficulty: 'Medium',
    seedingRate: 671,
    soakHours: 12,
    germinationDays: 6,
    blackoutDays: 6,
    lightDays: 10,
    estimatedYieldPerTray: 477,
    pricePerTray: 18.00,
    price500g: 6.90,
    price1kg: 10.90,
    color: 'bg-red-100 text-red-800 border-red-200',
    summary: 'Creamy, earthy, nutty, slightly sweet taste.',
    imageUrl: '/images/crops/Adzuki_Red_Bean.PNG'
  },
  {
    id: 'alfalfa',
    name: 'Alfalfa',
    scientificName: 'Medicago sativa',
    difficulty: 'Easy',
    seedingRate: 37,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 5,
    estimatedYieldPerTray: 447,
    pricePerTray: 12.00,
    price500g: 8.90,
    price1kg: 15.00,
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    summary: 'Mild, fresh taste. High in vitamins.',
    imageUrl: '/images/crops/alfaalfa.PNG'
  },
  {
    id: 'amaranth',
    name: 'Red Amaranth',
    scientificName: 'Amaranthus tricolor',
    difficulty: 'Medium-Difficult',
    seedingRate: 24,
    soakHours: 0,
    germinationDays: 4,
    blackoutDays: 4,
    lightDays: 8,
    estimatedYieldPerTray: 127,
    pricePerTray: 16.00,
    price500g: 42.00,
    price1kg: 84.00,
    color: 'bg-rose-100 text-rose-800 border-rose-200',
    summary: 'Mild, slightly nutty. Red-pink stems.',
    imageUrl: '/images/crops/Red_Amaranth.png'
  },
  {
    id: 'arugula',
    name: 'Arugula Rocket',
    scientificName: 'Eruca vesicaria',
    difficulty: 'Easy',
    seedingRate: 36,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 5,
    estimatedYieldPerTray: 358,
    pricePerTray: 14.00,
    price500g: 16.50,
    price1kg: 30.00,
    color: 'bg-green-100 text-green-800 border-green-200',
    summary: 'Peppery, sour taste. Fast grower.',
    imageUrl: '/images/crops/arugula.PNG'
  },
  {
    id: 'asian-mix',
    name: 'Asian Micro Mix',
    scientificName: 'Mixed Varieties',
    difficulty: 'Medium',
    seedingRate: 37,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 5,
    estimatedYieldPerTray: 373,
    pricePerTray: 15.00,
    price500g: 23.00,
    price1kg: 45.00,
    color: 'bg-orange-100 text-orange-800 border-orange-200',
    summary: 'Spicy taste. Mix of red and green leaves.',
    imageUrl: '/images/crops/asian_micro_mix.PNG'
  },
  {
    id: 'basil-cinnamon',
    name: 'Basil Cinnamon',
    scientificName: 'Ocimum basilicum',
    difficulty: 'Intermediate',
    seedingRate: 22,
    soakHours: 0,
    germinationDays: 7,
    blackoutDays: 6,
    lightDays: 8,
    estimatedYieldPerTray: 149,
    pricePerTray: 18.00,
    price500g: 68.00,
    price1kg: 120.00,
    color: 'bg-purple-100 text-purple-800 border-purple-200',
    summary: 'Basilicious mint and fresh cinnamon taste.',
    imageUrl: '/images/crops/basil.PNG'
  },
  {
    id: 'beet-red',
    name: 'Beet Red',
    scientificName: 'Beta vulgaris',
    difficulty: 'Medium',
    seedingRate: 149,
    soakHours: 4,
    germinationDays: 5,
    blackoutDays: 5,
    lightDays: 10,
    estimatedYieldPerTray: 171,
    pricePerTray: 16.00,
    price500g: 16.90,
    price1kg: 30.00,
    color: 'bg-red-100 text-red-800 border-red-200',
    summary: 'Earthy flavor. Red stems.',
    imageUrl: '/images/crops/Beet_Red.PNG'
  },
  {
    id: 'beet-bulls',
    name: 'Beet Bulls Blood',
    scientificName: 'Beta vulgaris',
    difficulty: 'Medium',
    seedingRate: 149,
    soakHours: 4,
    germinationDays: 6,
    blackoutDays: 6,
    lightDays: 8,
    estimatedYieldPerTray: 171,
    pricePerTray: 16.00,
    price500g: 16.90,
    price1kg: 30.00,
    color: 'bg-rose-100 text-rose-800 border-rose-200',
    summary: 'Earthy flavor. Purple stems and leaves.',
    imageUrl: '/images/crops/Beet_bulls_blood.PNG'
  },
  {
    id: 'broccoli',
    name: 'Broccoli Calabrese',
    scientificName: 'Brassica oleracea',
    difficulty: 'Easy',
    seedingRate: 75,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 7,
    estimatedYieldPerTray: 395,
    pricePerTray: 14.00,
    price500g: 21.00,
    price1kg: 40.00,
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    summary: 'Cabbage taste. High yield.',
    imageUrl: '/images/crops/Broccoli.PNG'
  },
  {
    id: 'buckwheat',
    name: 'Buckwheat',
    scientificName: 'Fagopyrum',
    difficulty: 'Easy',
    seedingRate: 37,
    soakHours: 4,
    germinationDays: 4,
    blackoutDays: 4,
    lightDays: 6,
    estimatedYieldPerTray: 544,
    pricePerTray: 13.00,
    price500g: 14.75,
    price1kg: 24.95,
    color: 'bg-lime-100 text-lime-800 border-lime-200',
    summary: 'Green, salad taste. Pink stems.',
    imageUrl: '/images/crops/buckwheat.PNG'
  },
  {
    id: 'dill',
    name: 'Dill Dakota',
    scientificName: 'Anethum graveolens',
    difficulty: 'Medium',
    seedingRate: 49,
    soakHours: 0,
    germinationDays: 7,
    blackoutDays: 6,
    lightDays: 13,
    estimatedYieldPerTray: 167,
    pricePerTray: 16.00,
    price500g: 15.00,
    price1kg: 29.00,
    color: 'bg-green-100 text-green-800 border-green-200',
    summary: 'Sweet, savory, grassy lemon notes.',
    imageUrl: '/images/crops/Dill_Dakota.PNG'
  },
  {
    id: 'fenugreek',
    name: 'Fenugreek',
    scientificName: 'Trigonella foenum-graecum',
    difficulty: 'Easy',
    seedingRate: 75,
    soakHours: 6,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 6,
    estimatedYieldPerTray: 522,
    pricePerTray: 14.00,
    price500g: 16.90,
    price1kg: 30.00,
    color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    summary: 'Curry, garam masala taste.',
    imageUrl: '/images/crops/Fenugreek.PNG'
  },
  {
    id: 'kale',
    name: 'Kale Red Russian',
    scientificName: 'Brassica napus pabularia',
    difficulty: 'Easy',
    seedingRate: 43,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 5,
    estimatedYieldPerTray: 410,
    pricePerTray: 14.00,
    price500g: 23.30,
    price1kg: 40.00,
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    summary: 'Bitter, sweet taste. Purple stems.',
    imageUrl: '/images/crops/Kale_Red_Russian.PNG'
  },
  {
    id: 'kohlrabi',
    name: 'Kohlrabi Red',
    scientificName: 'Brassica oleracea',
    difficulty: 'Easy',
    seedingRate: 42,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 4,
    estimatedYieldPerTray: 343,
    pricePerTray: 14.00,
    price500g: 14.60,
    price1kg: 26.00,
    color: 'bg-purple-100 text-purple-800 border-purple-200',
    summary: 'Light cabbage taste. Deep violet leaves.',
    imageUrl: '/images/crops/Kolhrabi.PNG'
  },
  {
    id: 'komatsuna',
    name: 'Komatsuna Red',
    scientificName: 'Brassica rapa',
    difficulty: 'Easy',
    seedingRate: 36,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 8,
    estimatedYieldPerTray: 447,
    pricePerTray: 14.00,
    price500g: 16.90,
    price1kg: 29.00,
    color: 'bg-red-100 text-red-800 border-red-200',
    summary: 'Mild sweetness. Green to purple leaves.',
    imageUrl: '/images/crops/Komatsuna.PNG'
  },
  {
    id: 'lemon-balm',
    name: 'Lemon Balm',
    scientificName: 'Melissa officinalis',
    difficulty: 'Difficult',
    seedingRate: 7,
    soakHours: 5,
    germinationDays: 12,
    blackoutDays: 12,
    lightDays: 14,
    estimatedYieldPerTray: 134,
    pricePerTray: 20.00,
    price500g: 79.90,
    price1kg: 149.50,
    color: 'bg-green-100 text-green-800 border-green-200',
    summary: 'Fresh lemon taste. Slow grower.',
    imageUrl: '/images/crops/Lemon_Balm.PNG'
  },
  {
    id: 'lentils',
    name: 'Lentils Red',
    scientificName: 'Lens culinaris',
    difficulty: 'Medium',
    seedingRate: 224,
    soakHours: 5,
    germinationDays: 4,
    blackoutDays: 4,
    lightDays: 6,
    estimatedYieldPerTray: 522,
    pricePerTray: 13.00,
    price500g: 4.50,
    price1kg: 7.50,
    color: 'bg-orange-100 text-orange-800 border-orange-200',
    summary: 'Neutral, raw taste.',
    imageUrl: '/images/crops/Lentils.PNG'
  },
  {
    id: 'lupine',
    name: 'Lupine',
    scientificName: 'Lupinus Lutus',
    difficulty: 'Medium',
    seedingRate: 343,
    soakHours: 8,
    germinationDays: 4,
    blackoutDays: 4,
    lightDays: 7,
    estimatedYieldPerTray: 522,
    pricePerTray: 16.00,
    price500g: 4.00,
    price1kg: 7.50,
    color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    summary: 'Umami mild nutty sweet taste.',
    imageUrl: '/images/crops/Lupine.PNG'
  },
  {
    id: 'marigold',
    name: 'Marigold Beauty',
    scientificName: 'Calendula Officinalis',
    difficulty: 'Medium',
    seedingRate: 37,
    soakHours: 0,
    germinationDays: 5,
    blackoutDays: 5,
    lightDays: 7,
    estimatedYieldPerTray: 119,
    pricePerTray: 18.00,
    price500g: 36.00,
    price1kg: 70.00,
    color: 'bg-orange-100 text-orange-800 border-orange-200',
    summary: 'Citrus, spicy taste.',
    imageUrl: '/images/crops/Marigold_Beauty.PNG'
  },
  {
    id: 'melon',
    name: 'Melon Cantaloupe',
    scientificName: 'Cucumis Melo',
    difficulty: 'Medium',
    seedingRate: 224,
    soakHours: 2,
    germinationDays: 6,
    blackoutDays: 6,
    lightDays: 12,
    estimatedYieldPerTray: 253,
    pricePerTray: 16.00,
    price500g: 39.50,
    price1kg: 78.90,
    color: 'bg-green-100 text-green-800 border-green-200',
    summary: 'Sweet, crispy taste.',
    imageUrl: '/images/crops/Melon_Cantaloupe.PNG'
  },
  {
    id: 'mizuna',
    name: 'Mizuna Green',
    scientificName: 'Brassica rapa nipposinica',
    difficulty: 'Easy',
    seedingRate: 27,
    soakHours: 0,
    germinationDays: 4,
    blackoutDays: 4,
    lightDays: 6,
    estimatedYieldPerTray: 462,
    pricePerTray: 14.00,
    price500g: 19.90,
    price1kg: 39.00,
    color: 'bg-lime-100 text-lime-800 border-lime-200',
    summary: 'Spicy taste. White green stems.',
    imageUrl: '/images/crops/Mizuna_Green.PNG'
  },
  {
    id: 'mung',
    name: 'Mung Bean',
    scientificName: 'Vigna radiata',
    difficulty: 'Medium',
    seedingRate: 320,
    soakHours: 8,
    germinationDays: 4,
    blackoutDays: 4,
    lightDays: 5,
    estimatedYieldPerTray: 596,
    pricePerTray: 13.00,
    price500g: 3.60,
    price1kg: 6.80,
    color: 'bg-green-100 text-green-800 border-green-200',
    summary: 'Neutral taste. Crunchy.',
    imageUrl: '/images/crops/Mung_Bean.PNG'
  },
  {
    id: 'mustard',
    name: 'Mustard Red Giant',
    scientificName: 'Brassica juncea',
    difficulty: 'Easy',
    seedingRate: 52,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 6,
    estimatedYieldPerTray: 447,
    pricePerTray: 14.00,
    price500g: 16.90,
    price1kg: 30.00,
    color: 'bg-red-100 text-red-800 border-red-200',
    summary: 'Spicy taste. Red leaves.',
    imageUrl: '/images/crops/Mustard_Red_Giant.PNG'
  },
  {
    id: 'popcorn',
    name: 'Popcorn',
    scientificName: 'Zea Mays',
    difficulty: 'Medium',
    seedingRate: 469,
    soakHours: 10,
    germinationDays: 5,
    blackoutDays: 5,
    lightDays: 10,
    estimatedYieldPerTray: 559,
    pricePerTray: 14.00,
    price500g: 7.85,
    price1kg: 12.90,
    color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    summary: 'Sugary, sweet taste. Yellow shoots.',
    imageUrl: '/images/crops/PopCorn.PNG'
  },
  {
    id: 'daikon',
    name: 'Radish Daikon',
    scientificName: 'Raphanus sativus',
    difficulty: 'Easy',
    seedingRate: 52,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 5,
    estimatedYieldPerTray: 529,
    pricePerTray: 13.00,
    price500g: 11.00,
    price1kg: 20.10,
    color: 'bg-white text-slate-800 border-slate-200',
    summary: 'Spicy taste. White stems.',
    imageUrl: '/images/crops/Radish_Daikon.PNG'
  },
  {
    id: 'rambo',
    name: 'Radish Red Rambo',
    scientificName: 'Raphanus sativus',
    difficulty: 'Easy',
    seedingRate: 52,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 6,
    estimatedYieldPerTray: 492,
    pricePerTray: 15.00,
    price500g: 17.50,
    price1kg: 31.20,
    color: 'bg-rose-100 text-rose-800 border-rose-200',
    summary: 'Spicy taste. Deep purple leaves.',
    imageUrl: '/images/crops/Radish_Red_Rambo.PNG'
  },
  {
    id: 'sorrel',
    name: 'Sorrel Red Veined',
    scientificName: 'Rumex sanguineus',
    difficulty: 'Difficult',
    seedingRate: 4,
    soakHours: 0,
    germinationDays: 9,
    blackoutDays: 7,
    lightDays: 14,
    estimatedYieldPerTray: 42,
    pricePerTray: 22.00,
    price500g: 35.45,
    price1kg: 69.45,
    pkgWeightSmall: 50,
    pkgWeightLarge: 100,
    color: 'bg-red-100 text-red-800 border-red-200',
    summary: 'Lemony, sour taste. Red veins.',
    imageUrl: '/images/crops/Sorrel_Red_Veined.PNG'
  },
  {
    id: 'sunflower',
    name: 'Sunflower Big',
    scientificName: 'Helianthus annuus',
    difficulty: 'Medium',
    seedingRate: 224,
    soakHours: 6,
    germinationDays: 4,
    blackoutDays: 4,
    lightDays: 5,
    estimatedYieldPerTray: 708,
    pricePerTray: 15.00,
    price500g: 4.95,
    price1kg: 9.20,
    color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    summary: 'Sweet taste. Crunchy.',
    imageUrl: '/images/crops/Sunflower_Big.PNG'
  },
  {
    id: 'turnip',
    name: 'Turnip',
    scientificName: 'Brassica rapa',
    difficulty: 'Easy',
    seedingRate: 36,
    soakHours: 0,
    germinationDays: 3,
    blackoutDays: 3,
    lightDays: 5,
    estimatedYieldPerTray: 462,
    pricePerTray: 13.00,
    price500g: 9.00,
    price1kg: 16.00,
    color: 'bg-purple-100 text-purple-800 border-purple-200',
    summary: 'Sweet with pepper spice.',
    imageUrl: '/images/crops/Turnip.PNG'
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust1',
    name: 'The Local Bistro',
    type: 'Restaurant',
    contact: 'Chef Marco',
    email: 'marco@localbistro.com',
    notes: 'Likes spicy radish mix on Tuesdays.'
  },
  {
    id: 'cust2',
    name: 'Green Market Stand',
    type: 'Individual',
    contact: 'Sarah',
    email: 'sarah@market.com',
    notes: 'Saturday farmers market sales.'
  }
];

/**
 * Tray Specifications
 * Standard tray used: 10x20 shallow tray
 * Dimensions: 35cm (width) x 55cm (height)
 * Area: 1,925 cm² (49% larger than standard 10"x20" = 1,290 cm²)
 */
export const TRAY_SPECS = {
  type: '10x20 shallow tray',
  widthCm: 35,
  heightCm: 55,
  widthInches: 13.78, // ~35cm
  heightInches: 21.65, // ~55cm
  areaCm2: 1925, // 35cm × 55cm
  areaRatio: 1.49, // Ratio compared to standard 10"x20" tray
} as const;

export const STAGE_FLOW = [
  Stage.SEED,
  Stage.SOAK,
  Stage.GERMINATION,
  Stage.BLACKOUT,
  Stage.LIGHT,
  Stage.HARVEST_READY,
  Stage.HARVESTED
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 't1', date: '2023-10-01', type: 'expense', category: 'Seeds', amount: 150, description: 'Bulk Sunflower Seeds' },
  { id: 't2', date: '2023-10-02', type: 'expense', category: 'Supplies', amount: 45, description: 'Coco Coir Bricks' },
  { id: 't3', date: '2023-10-10', type: 'income', category: 'Sales', amount: 200, description: 'Farmers Market Weekend', customerId: 'cust2' },
  { id: 't4', date: '2023-10-15', type: 'income', category: 'Restaurant', amount: 120, description: 'Weekly Order', customerId: 'cust1' },
];
